### ISSUE TITLE
Cannot find module 'yargs'

### ISSUE THREAD

**Issue by lucraraujo** [rafamel/yaml-import#1]
I tried to use the the standalone CLI command to import some yaml into another, but this error happened;
I saw that the lib yargs is a dev dependency.

**Comment by rafamel** [comment]
Sorry about this, yargs was indeed incorrectly marked as a dev dependency. It has been fixed and the cli should be working as intended. Blame's on me for not testing it properly.

Thank you for reporting it, Lucas!
