### ISSUE TITLE
Support relative paths

### ISSUE THREAD

**Issue by danfsd** [rafamel/yaml-import#19]
Hello,

I would like to suggest the support for relative paths when importing other YAML files.
This could work based on the input file's directory like so:

Example of directory structure:

```
main-folder/
|__ sub-folder/
    |__ bar.yml
    |__ baz.yml
|__ foo.yml
```

```yaml
# bar.yml

# Importing file on previous directory
!!import/single ../foo.yml
# Importing file in same directory. Probably could accept simply "baz.yml" as well
!!import/single ./baz.yml

# ...
```

So that when the user ran`yimp -i sub-folder/bar.yml` the `foo.yml` file on the root directory could be imported.

**Comment by rafamel** [comment]
Hello @danfsd, this should already be supported. See for example [this file](https://github.com/rafamel/yaml-import/blob/master/test/fixtures/foo/bar/a.yml) in the integration tests. For additional details, check the [relevant docs on this.](https://github.com/rafamel/yaml-import/blob/master/README.md#yaml)
